import pytest
from pathlib import Path
from unittest.mock import MagicMock
import backend.cognitive.file_generator as fg

def test_file_generator_success(monkeypatch, tmp_path):
    mock_kb = tmp_path / "knowledge_base"
    monkeypatch.setattr(fg, "_get_kb", lambda: mock_kb)
    
    # Mock LLM Client
    class MockClient:
        def chat(self, messages, temperature):
            return "Mocked file content"
            
    monkeypatch.setattr("llm_orchestrator.factory.get_kimi_client", lambda: MockClient())
    
    # Mock integrations
    import sys
    sys.modules["api.docs_library_api"] = MagicMock()
    sys.modules["cognitive.librarian_autonomous"] = MagicMock()
    sys.modules["cognitive.magma_bridge"] = MagicMock()
    sys.modules["api._genesis_tracker"] = MagicMock()
    
    generator = fg.get_file_generator()
    res = generator.generate(
        prompt="Make a python script",
        filename="test_script.py",
        folder="scripts",
        file_type="auto",
        use_kimi=True
    )
    
    assert res["success"] is True
    assert res["filename"] == "test_script.py"
    assert res["file_type"] == "python"
    
    expected_path = mock_kb / "scripts" / "test_script.py"
    assert expected_path.exists()
    assert expected_path.read_text(encoding="utf-8") == "Mocked file content"

def test_file_generator_pdf(monkeypatch, tmp_path):
    mock_kb = tmp_path / "knowledge_base"
    monkeypatch.setattr(fg, "_get_kb", lambda: mock_kb)

    class MockClient:
        def chat(self, messages, temperature):
            return "PDF content text"
            
    monkeypatch.setattr("llm_orchestrator.factory.get_kimi_client", lambda: MockClient())

    import sys
    for m in ["api.docs_library_api", "cognitive.librarian_autonomous", "cognitive.magma_bridge", "api._genesis_tracker"]:
        sys.modules[m] = MagicMock()

    generator = fg.get_file_generator()
    res = generator.generate(
        prompt="Make a doc",
        filename="report.pdf",
        folder="",
        file_type="auto",
        use_kimi=True
    )
    
    assert res["success"] is True
    assert res["file_type"] == "pdf"
    
    expected_path = mock_kb / "report.pdf.txt"
    assert expected_path.exists()
    content = expected_path.read_text(encoding="utf-8")
    assert "PDF content text" in content
    assert "Generated by Grace AI" in content

if __name__ == "__main__":
    pytest.main(['-v', __file__])
