"""
LLM Orchestration Connector - Multi-LLM Coordination

Connects LLM orchestration to Layer 1 message bus for:
- Skill-aware LLM selection
- Procedural memory integration
- Cross-component reasoning
"""

from typing import Dict, Any, Optional
import logging
from datetime import datetime

from layer1.message_bus import (
    Layer1MessageBus,
    ComponentType,
    Message,
    get_message_bus
)

logger = logging.getLogger(__name__)


class LLMOrchestrationConnector:
    """
    Connects LLM Orchestration to Layer 1 message bus.

    Autonomous Actions:
    1. New procedure created → Register as available skill
    2. Query requires skill → Auto-select LLM with that skill
    3. LLM response → Evaluate and send feedback to memory mesh
    4. Pattern detected → Adapt LLM selection strategy
    """

    def __init__(
        self,
        llm_orchestrator,
        message_bus: Optional[Layer1MessageBus] = None
    ):
        self.llm_orchestrator = llm_orchestrator
        self.message_bus = message_bus or get_message_bus()

        # Track available skills
        self.available_skills: Dict[str, Dict[str, Any]] = {}

        # Register component
        self.message_bus.register_component(
            ComponentType.LLM_ORCHESTRATION,
            self.llm_orchestrator
        )

        logger.info("[LLM-ORCHESTRATION-CONNECTOR] Registered with message bus")

        # Set up autonomous actions
        self._register_autonomous_actions()
        self._register_request_handlers()
        self._subscribe_to_events()

    # ================================================================
    # AUTONOMOUS ACTIONS
    # ================================================================

    def _register_autonomous_actions(self):
        """Register all autonomous actions for LLM orchestration."""

        # 1. Auto-register new skills
        self.message_bus.register_autonomous_action(
            trigger_event="memory_mesh.procedure_created",
            action=self._on_procedure_created,
            component=ComponentType.LLM_ORCHESTRATION,
            description="Auto-register new procedural skills"
        )

        # 2. Auto-evaluate LLM responses
        self.message_bus.register_autonomous_action(
            trigger_event="llm_orchestration.response_generated",
            action=self._on_response_generated,
            component=ComponentType.LLM_ORCHESTRATION,
            description="Auto-evaluate and send feedback"
        )

        logger.info("[LLM-ORCHESTRATION-CONNECTOR] ⭐ Registered 2 autonomous actions")

    # ================================================================
    # EVENT HANDLERS (Autonomous)
    # ================================================================

    async def _on_procedure_created(self, message: Message):
        """Handle new procedure - register as skill."""
        procedure_name = message.payload.get("procedure_name")
        procedure_id = message.payload.get("procedure_id")
        trust_score = message.payload.get("trust_score")

        logger.info(
            f"[LLM-ORCHESTRATION-CONNECTOR] 🤖 New skill registered: {procedure_name} "
            f"(trust: {trust_score:.2f})"
        )

        # Register skill
        self.available_skills[procedure_name] = {
            "procedure_id": procedure_id,
            "trust_score": trust_score,
            "registered_at": datetime.utcnow().isoformat()
        }

        # Publish skill registered event
        await self.message_bus.publish(
            topic="llm_orchestration.skill_registered",
            payload={
                "skill_name": procedure_name,
                "procedure_id": procedure_id,
                "trust_score": trust_score,
                "total_skills": len(self.available_skills)
            },
            from_component=ComponentType.LLM_ORCHESTRATION
        )

    async def _on_response_generated(self, message: Message):
        """Handle LLM response - auto-evaluate."""
        query = message.payload.get("query")
        response = message.payload.get("response")
        llm_used = message.payload.get("llm_used")
        confidence = message.payload.get("confidence", 0.8)

        logger.info(
            f"[LLM-ORCHESTRATION-CONNECTOR] 🤖 Response generated by {llm_used} "
            f"(confidence: {confidence:.2f})"
        )

        # Send evaluation feedback to memory mesh
        await self.message_bus.publish(
            topic="memory_mesh.llm_response_feedback",
            payload={
                "query": query,
                "llm_used": llm_used,
                "confidence": confidence,
                "success": confidence >= 0.7,
                "timestamp": datetime.utcnow().isoformat()
            },
            from_component=ComponentType.LLM_ORCHESTRATION
        )

    # ================================================================
    # REQUEST HANDLERS
    # ================================================================

    def _register_request_handlers(self):
        """Register request handlers for other components."""

        self.message_bus.register_request_handler(
            component=ComponentType.LLM_ORCHESTRATION,
            topic="generate_response",
            handler=self._handle_generate_response
        )

        self.message_bus.register_request_handler(
            component=ComponentType.LLM_ORCHESTRATION,
            topic="register_new_skill",
            handler=self._handle_register_skill
        )

        self.message_bus.register_request_handler(
            component=ComponentType.LLM_ORCHESTRATION,
            topic="get_available_skills",
            handler=self._handle_get_skills
        )

        logger.info("[LLM-ORCHESTRATION-CONNECTOR] 🔧 Registered 3 request handlers")

    async def _handle_generate_response(self, message: Message) -> Dict[str, Any]:
        """Handle response generation request."""
        query = message.payload.get("query")
        context = message.payload.get("context", {})
        required_skill = message.payload.get("required_skill")

        # Get retrieval context from RAG
        try:
            rag_response = await self.message_bus.request(
                to_component=ComponentType.RAG,
                topic="retrieve_with_context",
                payload={
                    "query": query,
                    "top_k": 5
                },
                from_component=ComponentType.LLM_ORCHESTRATION,
                timeout=10.0
            )

            retrieval_results = rag_response.get("results", [])

        except Exception as e:
            logger.error(f"[LLM-ORCHESTRATION-CONNECTOR] RAG retrieval failed: {e}")
            retrieval_results = []

        # Select LLM based on skill
        llm_used = self._select_llm(required_skill)

        # Generate response (simplified)
        response = f"Response from {llm_used} to: {query}"
        confidence = 0.85

        # Trigger response generated event
        await self.message_bus.publish(
            topic="llm_orchestration.response_generated",
            payload={
                "query": query,
                "response": response,
                "llm_used": llm_used,
                "confidence": confidence
            },
            from_component=ComponentType.LLM_ORCHESTRATION
        )

        return {
            "response": response,
            "llm_used": llm_used,
            "confidence": confidence,
            "retrieval_context": len(retrieval_results)
        }

    async def _handle_register_skill(self, message: Message) -> Dict[str, Any]:
        """Handle skill registration command."""
        skill_name = message.payload.get("skill_name")
        procedure_id = message.payload.get("procedure_id")
        trust_score = message.payload.get("trust_score")

        # Register skill
        self.available_skills[skill_name] = {
            "procedure_id": procedure_id,
            "trust_score": trust_score,
            "registered_at": datetime.utcnow().isoformat()
        }

        logger.info(
            f"[LLM-ORCHESTRATION-CONNECTOR] ✓ Skill registered: {skill_name}"
        )

        return {
            "skill_name": skill_name,
            "registered": True,
            "total_skills": len(self.available_skills)
        }

    async def _handle_get_skills(self, message: Message) -> Dict[str, Any]:
        """Handle get available skills request."""
        return {
            "total_skills": len(self.available_skills),
            "skills": [
                {
                    "name": name,
                    "trust_score": info["trust_score"],
                    "procedure_id": info["procedure_id"]
                }
                for name, info in self.available_skills.items()
            ]
        }

    # ================================================================
    # SUBSCRIPTIONS
    # ================================================================

    def _subscribe_to_events(self):
        """Subscribe to events from other components."""

        # Listen for pattern detection
        self.message_bus.subscribe(
            topic="autonomous_learning.new_pattern",
            handler=self._on_pattern_detected
        )

        logger.info("[LLM-ORCHESTRATION-CONNECTOR] 📡 Subscribed to 1 event topic")

    async def _on_pattern_detected(self, message: Message):
        """Handle pattern detection - adapt LLM selection."""
        pattern_type = message.payload.get("pattern_type")

        logger.info(
            f"[LLM-ORCHESTRATION-CONNECTOR] 📊 Pattern detected: {pattern_type}"
        )

        # Could adapt LLM selection strategy based on patterns
        # For now, just log

    # ================================================================
    # UTILITIES
    # ================================================================

    def _select_llm(self, required_skill: Optional[str] = None) -> str:
        """Select LLM based on required skill."""
        if required_skill and required_skill in self.available_skills:
            # Use specialized LLM for this skill
            return f"specialized-llm-{required_skill}"
        else:
            # Use general LLM
            return "general-llm"


def create_llm_orchestration_connector(
    llm_orchestrator,
    message_bus: Optional[Layer1MessageBus] = None
) -> LLMOrchestrationConnector:
    """Create and initialize LLM orchestration connector."""
    connector = LLMOrchestrationConnector(llm_orchestrator, message_bus)
    logger.info("[LLM-ORCHESTRATION-CONNECTOR] ✓ Initialized and connected to message bus")
    return connector
