import logging
import asyncio
import json
import hashlib
from typing import Dict, Any, List, Optional, Tuple, Set
from dataclasses import dataclass, field
from enum import Enum
from datetime import datetime, timedelta
from pathlib import Path
import uuid

logger = logging.getLogger(__name__)


class InsightType(str, Enum):
    """Types of insights the Oracle can generate."""
    PATTERN = "pattern"               # Recurring code patterns
    FAILURE_PREDICTION = "failure"    # Predicted failures
    OPTIMIZATION = "optimization"     # Performance improvements
    SECURITY = "security"             # Security concerns
    ARCHITECTURE = "architecture"     # Design patterns
    DEPENDENCY = "dependency"         # Dependency issues
    CASCADING_RISK = "cascading"      # Cascading failure risk
    USER_INTENT = "user_intent"       # Predicted user needs


class ConfidenceLevel(str, Enum):
    """Confidence levels for predictions."""
    CERTAIN = "certain"       # 95%+ confidence
    HIGH = "high"             # 80-95%
    MEDIUM = "medium"         # 60-80%
    LOW = "low"               # 40-60%
    SPECULATIVE = "speculative"  # <40%


@dataclass
class OracleInsight:
    """An insight generated by the Oracle."""
    insight_id: str
    insight_type: InsightType
    title: str
    description: str
    confidence: ConfidenceLevel
    confidence_score: float
    affected_files: List[str] = field(default_factory=list)
    affected_functions: List[str] = field(default_factory=list)
    prediction_horizon: int = 1  # How many steps ahead (1-7)
    prevention_actions: List[str] = field(default_factory=list)
    genesis_key_id: Optional[str] = None
    source_patterns: List[str] = field(default_factory=list)
    created_at: datetime = field(default_factory=datetime.utcnow)
    expires_at: Optional[datetime] = None
    is_active: bool = True
    was_accurate: Optional[bool] = None  # For learning

    def to_dict(self) -> Dict[str, Any]:
        return {
            "insight_id": self.insight_id,
            "type": self.insight_type.value,
            "title": self.title,
            "description": self.description,
            "confidence": self.confidence.value,
            "confidence_score": self.confidence_score,
            "affected_files": self.affected_files,
            "affected_functions": self.affected_functions,
            "prediction_horizon": self.prediction_horizon,
            "prevention_actions": self.prevention_actions,
            "genesis_key_id": self.genesis_key_id,
            "created_at": self.created_at.isoformat(),
            "is_active": self.is_active
        }


@dataclass
class ResearchEntry:
    """An entry in the AI research knowledge base."""
    research_id: str
    topic: str
    findings: str
    code_examples: List[str] = field(default_factory=list)
    patterns_discovered: List[str] = field(default_factory=list)
    failure_patterns: List[str] = field(default_factory=list)
    success_patterns: List[str] = field(default_factory=list)
    genesis_key_id: Optional[str] = None
    source_files: List[str] = field(default_factory=list)
    confidence: float = 0.0
    usage_count: int = 0
    last_validated: Optional[datetime] = None
    created_at: datetime = field(default_factory=datetime.utcnow)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "research_id": self.research_id,
            "topic": self.topic,
            "findings": self.findings[:500],
            "patterns_discovered": self.patterns_discovered,
            "failure_patterns": self.failure_patterns,
            "success_patterns": self.success_patterns,
            "genesis_key_id": self.genesis_key_id,
            "confidence": self.confidence,
            "usage_count": self.usage_count,
            "created_at": self.created_at.isoformat()
        }


@dataclass
class ForwardSimulation:
    """Result of thinking N steps ahead."""
    simulation_id: str
    current_state: str
    steps: List[Dict[str, Any]] = field(default_factory=list)
    predicted_outcomes: List[str] = field(default_factory=list)
    risk_points: List[Dict[str, Any]] = field(default_factory=list)
    recommended_path: List[str] = field(default_factory=list)
    cascading_risks: List[str] = field(default_factory=list)
    confidence: float = 0.0
    depth: int = 7


class OracleCore:
    """
    The Oracle - Grace's predictive intelligence system.

    Capabilities:
    1. 7-step forward simulation (chess-like thinking)
    2. Cascading failure prediction and prevention
    3. Pattern recognition from code history
    4. Proactive learning from all interactions
    5. Research storage with Genesis key tracking
    6. User intent prediction
    """

    def __init__(
        self,
        session=None,
        genesis_service=None,
        learning_memory=None,
        vector_db=None,
        repo_path: Optional[Path] = None
    ):
        self.session = session
        self._genesis_service = genesis_service
        self._learning_memory = learning_memory
        self._vector_db = vector_db
        self.repo_path = repo_path or Path.cwd()

        # Research storage path
        self.research_path = self.repo_path / "ai_research"
        self.research_path.mkdir(parents=True, exist_ok=True)

        # Insight storage
        self._insights: Dict[str, OracleInsight] = {}
        self._research: Dict[str, ResearchEntry] = {}

        # Pattern recognition
        self._code_patterns: Dict[str, List[str]] = {}  # pattern_hash -> occurrences
        self._failure_patterns: Dict[str, Dict[str, Any]] = {}
        self._success_patterns: Dict[str, Dict[str, Any]] = {}

        # Forward simulation cache
        self._simulation_cache: Dict[str, ForwardSimulation] = {}

        # Learning state
        self._learning_queue: List[Dict[str, Any]] = []
        self._prediction_accuracy: List[Tuple[str, bool]] = []  # For calibration

        # Metrics
        self.metrics = {
            "insights_generated": 0,
            "research_entries": 0,
            "predictions_made": 0,
            "predictions_correct": 0,
            "cascading_failures_prevented": 0,
            "patterns_discovered": 0
        }

        logger.info("[ORACLE] Core intelligence initialized")

    async def analyze_and_predict(
        self,
        code: str,
        context: Optional[str] = None,
        file_path: Optional[str] = None,
        user_intent: Optional[str] = None
    ) -> List[OracleInsight]:
        """
        Analyze code and generate predictive insights.

        This is the main entry point for the Oracle's analysis.
        """
        insights = []

        # Generate insight ID base
        analysis_id = f"ANALYZE-{uuid.uuid4().hex[:8]}"

        try:
            # 1. Pattern Recognition
            pattern_insights = await self._recognize_patterns(code, file_path)
            insights.extend(pattern_insights)

            # 2. Forward Simulation (7 steps ahead)
            simulation = await self._simulate_forward(code, context, 7)
            if simulation.risk_points:
                for risk in simulation.risk_points:
                    insight = OracleInsight(
                        insight_id=f"RISK-{uuid.uuid4().hex[:8]}",
                        insight_type=InsightType.FAILURE_PREDICTION,
                        title=risk.get("title", "Predicted Issue"),
                        description=risk.get("description", ""),
                        confidence=self._score_to_level(risk.get("probability", 0.5)),
                        confidence_score=risk.get("probability", 0.5),
                        prediction_horizon=risk.get("step", 1),
                        prevention_actions=risk.get("prevention", []),
                        affected_files=[file_path] if file_path else []
                    )
                    insights.append(insight)

            # 3. Cascading Failure Analysis
            cascading = await self._analyze_cascading_risks(code, file_path)
            insights.extend(cascading)

            # 4. User Intent Prediction
            if user_intent:
                intent_insights = await self._predict_user_needs(user_intent, code)
                insights.extend(intent_insights)

            # 5. Store insights with Genesis keys
            for insight in insights:
                self._insights[insight.insight_id] = insight
                await self._create_insight_genesis_key(insight)

            self.metrics["insights_generated"] += len(insights)
            self.metrics["predictions_made"] += len([i for i in insights if i.insight_type == InsightType.FAILURE_PREDICTION])

        except Exception as e:
            logger.error(f"[ORACLE] Analysis failed: {e}")

        return insights

    async def think_ahead(
        self,
        current_action: str,
        context: str,
        depth: int = 7
    ) -> ForwardSimulation:
        """
        Think N steps ahead like a chess grandmaster.

        Simulates potential outcomes of an action and identifies
        risks, opportunities, and optimal paths.
        """
        simulation = ForwardSimulation(
            simulation_id=f"SIM-{uuid.uuid4().hex[:12]}",
            current_state=current_action,
            depth=min(depth, 7)
        )

        # Build decision tree
        current_states = [{"state": current_action, "context": context, "step": 0}]

        for step in range(1, depth + 1):
            next_states = []

            for state in current_states:
                # Predict next possible states
                outcomes = await self._predict_next_states(state, step)

                for outcome in outcomes:
                    simulation.steps.append({
                        "step": step,
                        "from_state": state["state"][:100],
                        "to_state": outcome["state"][:100],
                        "probability": outcome["probability"],
                        "is_risky": outcome.get("is_risky", False)
                    })

                    # Track risks
                    if outcome.get("is_risky"):
                        simulation.risk_points.append({
                            "step": step,
                            "title": outcome.get("risk_title", "Potential Issue"),
                            "description": outcome.get("risk_description", ""),
                            "probability": outcome["probability"],
                            "prevention": outcome.get("prevention", [])
                        })

                    # Track cascading risks
                    if outcome.get("cascading_risk"):
                        simulation.cascading_risks.append(outcome["cascading_risk"])

                    next_states.append({
                        "state": outcome["state"],
                        "context": state["context"],
                        "step": step
                    })

            current_states = next_states[:5]  # Limit branching

        # Determine recommended path
        simulation.recommended_path = self._find_optimal_path(simulation)
        simulation.confidence = self._calculate_simulation_confidence(simulation)

        # Cache simulation
        self._simulation_cache[simulation.simulation_id] = simulation

        return simulation

    async def _recognize_patterns(
        self,
        code: str,
        file_path: Optional[str]
    ) -> List[OracleInsight]:
        """Recognize patterns in code and match against known patterns."""
        insights = []

        # Extract code patterns
        patterns = self._extract_patterns(code)

        for pattern_type, pattern_value in patterns.items():
            pattern_hash = hashlib.md5(f"{pattern_type}:{pattern_value}".encode()).hexdigest()[:12]

            # Check against known failure patterns
            if pattern_hash in self._failure_patterns:
                failure_info = self._failure_patterns[pattern_hash]
                insights.append(OracleInsight(
                    insight_id=f"PAT-{uuid.uuid4().hex[:8]}",
                    insight_type=InsightType.PATTERN,
                    title=f"Known failure pattern: {pattern_type}",
                    description=failure_info.get("description", "This pattern has caused issues before"),
                    confidence=ConfidenceLevel.HIGH,
                    confidence_score=failure_info.get("confidence", 0.8),
                    prevention_actions=failure_info.get("fixes", []),
                    source_patterns=[pattern_hash],
                    affected_files=[file_path] if file_path else []
                ))

            # Track pattern for learning
            if pattern_hash not in self._code_patterns:
                self._code_patterns[pattern_hash] = []
            self._code_patterns[pattern_hash].append({
                "file": file_path,
                "timestamp": datetime.utcnow().isoformat()
            })

        self.metrics["patterns_discovered"] = len(self._code_patterns)

        return insights

    def _extract_patterns(self, code: str) -> Dict[str, str]:
        """Extract recognizable patterns from code."""
        import re
        patterns = {}

        # Error handling patterns
        if "except:" in code and "except Exception" not in code:
            patterns["bare_except"] = "bare except clause"

        if "try:" in code and "finally:" not in code:
            patterns["try_no_finally"] = "try without finally for cleanup"

        # Null safety patterns
        null_checks = len(re.findall(r'if\s+\w+\s+is\s+(not\s+)?None', code))
        if null_checks == 0 and "." in code:
            patterns["no_null_checks"] = "potential null dereference"

        # Import patterns
        if "import *" in code:
            patterns["star_import"] = "wildcard import"

        # Security patterns
        if "eval(" in code or "exec(" in code:
            patterns["dangerous_eval"] = "use of eval/exec"

        if "password" in code.lower() and "=" in code:
            patterns["hardcoded_secret"] = "potential hardcoded password"

        # Performance patterns
        if "+=" in code and "for" in code and "str" in code.lower():
            patterns["string_concat_loop"] = "string concatenation in loop"

        # Complexity patterns
        indent_levels = max((len(line) - len(line.lstrip())) // 4 for line in code.split("\n") if line.strip())
        if indent_levels > 5:
            patterns["deep_nesting"] = f"deep nesting ({indent_levels} levels)"

        return patterns

    async def _simulate_forward(
        self,
        code: str,
        context: Optional[str],
        depth: int
    ) -> ForwardSimulation:
        """Run forward simulation on code changes."""
        return await self.think_ahead(
            current_action=f"Code change: {code[:200]}...",
            context=context or "Code modification",
            depth=depth
        )

    async def _predict_next_states(
        self,
        current_state: Dict[str, Any],
        step: int
    ) -> List[Dict[str, Any]]:
        """Predict possible next states from current state."""
        outcomes = []

        state_text = current_state["state"]

        # Heuristic predictions based on patterns
        if "error" in state_text.lower() or "exception" in state_text.lower():
            outcomes.append({
                "state": "Error propagates to caller",
                "probability": 0.7,
                "is_risky": True,
                "risk_title": "Error Propagation",
                "risk_description": "Unhandled error may cascade",
                "prevention": ["Add try-except", "Add error boundary"],
                "cascading_risk": "Error may affect downstream components"
            })

        if "database" in state_text.lower() or "query" in state_text.lower():
            outcomes.append({
                "state": "Database operation executes",
                "probability": 0.8,
                "is_risky": False
            })
            outcomes.append({
                "state": "Database connection fails",
                "probability": 0.1,
                "is_risky": True,
                "risk_title": "Database Failure",
                "risk_description": "Connection or query may fail",
                "prevention": ["Add connection retry", "Add timeout handling"]
            })

        if "import" in state_text.lower():
            outcomes.append({
                "state": "Module loads successfully",
                "probability": 0.9,
                "is_risky": False
            })
            outcomes.append({
                "state": "Import fails - module not found",
                "probability": 0.1,
                "is_risky": True,
                "risk_title": "Import Error",
                "risk_description": "Missing dependency",
                "prevention": ["Add to requirements", "Add import check"]
            })

        if "async" in state_text.lower() or "await" in state_text.lower():
            outcomes.append({
                "state": "Async operation completes",
                "probability": 0.75,
                "is_risky": False
            })
            outcomes.append({
                "state": "Async operation hangs",
                "probability": 0.15,
                "is_risky": True,
                "risk_title": "Async Deadlock",
                "risk_description": "Operation may hang indefinitely",
                "prevention": ["Add timeout", "Add cancellation token"]
            })

        # Default successful outcome
        if not outcomes:
            outcomes.append({
                "state": f"Step {step} completes normally",
                "probability": 0.8,
                "is_risky": False
            })

        return outcomes

    async def _analyze_cascading_risks(
        self,
        code: str,
        file_path: Optional[str]
    ) -> List[OracleInsight]:
        """Analyze code for cascading failure risks."""
        insights = []

        # Identify dependency chains
        dependencies = self._identify_dependencies(code)

        for dep_chain in dependencies:
            if len(dep_chain) > 3:  # Long dependency chains are risky
                insights.append(OracleInsight(
                    insight_id=f"CASCADE-{uuid.uuid4().hex[:8]}",
                    insight_type=InsightType.CASCADING_RISK,
                    title="Long Dependency Chain Detected",
                    description=f"Chain of {len(dep_chain)} dependencies: {' → '.join(dep_chain[:5])}...",
                    confidence=ConfidenceLevel.MEDIUM,
                    confidence_score=0.7,
                    prediction_horizon=3,
                    prevention_actions=[
                        "Add circuit breaker pattern",
                        "Add fallback mechanisms",
                        "Consider breaking the chain"
                    ],
                    affected_files=[file_path] if file_path else []
                ))

        # Check for single points of failure
        spof = self._find_single_points_of_failure(code)
        for point in spof:
            insights.append(OracleInsight(
                insight_id=f"SPOF-{uuid.uuid4().hex[:8]}",
                insight_type=InsightType.CASCADING_RISK,
                title=f"Single Point of Failure: {point['name']}",
                description=point["description"],
                confidence=ConfidenceLevel.HIGH,
                confidence_score=0.85,
                prediction_horizon=1,
                prevention_actions=point["mitigation"],
                affected_functions=[point["name"]]
            ))

        return insights

    def _identify_dependencies(self, code: str) -> List[List[str]]:
        """Identify dependency chains in code."""
        import re
        chains = []

        # Find function calls
        calls = re.findall(r'(\w+)\s*\(', code)

        # Simple chain detection
        if len(calls) > 3:
            chains.append(calls[:7])  # First 7 as a chain

        return chains

    def _find_single_points_of_failure(self, code: str) -> List[Dict[str, Any]]:
        """Find single points of failure in code."""
        spof = []

        # Database connections
        if "connection" in code.lower() and "pool" not in code.lower():
            spof.append({
                "name": "database_connection",
                "description": "Single database connection without pooling",
                "mitigation": ["Use connection pool", "Add connection retry logic"]
            })

        # API calls without retry
        if ("requests." in code or "http" in code.lower()) and "retry" not in code.lower():
            spof.append({
                "name": "api_call",
                "description": "API call without retry mechanism",
                "mitigation": ["Add retry with backoff", "Add circuit breaker"]
            })

        # File operations without error handling
        if ("open(" in code or "write(" in code) and "try" not in code:
            spof.append({
                "name": "file_operation",
                "description": "File operation without error handling",
                "mitigation": ["Wrap in try-except", "Use context manager"]
            })

        return spof

    async def _predict_user_needs(
        self,
        user_intent: str,
        code: str
    ) -> List[OracleInsight]:
        """Predict what the user might need next."""
        insights = []
        intent_lower = user_intent.lower()

        # Predict based on intent keywords
        if any(word in intent_lower for word in ["test", "testing"]):
            insights.append(OracleInsight(
                insight_id=f"INTENT-{uuid.uuid4().hex[:8]}",
                insight_type=InsightType.USER_INTENT,
                title="User likely needs test coverage",
                description="Based on intent, user may want to add tests",
                confidence=ConfidenceLevel.MEDIUM,
                confidence_score=0.7,
                prediction_horizon=2,
                prevention_actions=[
                    "Suggest test file creation",
                    "Identify untested functions",
                    "Propose test cases"
                ]
            ))

        if any(word in intent_lower for word in ["deploy", "production", "release"]):
            insights.append(OracleInsight(
                insight_id=f"INTENT-{uuid.uuid4().hex[:8]}",
                insight_type=InsightType.USER_INTENT,
                title="Pre-deployment checklist recommended",
                description="User appears to be preparing for deployment",
                confidence=ConfidenceLevel.HIGH,
                confidence_score=0.8,
                prediction_horizon=3,
                prevention_actions=[
                    "Run security scan",
                    "Check environment variables",
                    "Verify database migrations",
                    "Test rollback procedure"
                ]
            ))

        if any(word in intent_lower for word in ["performance", "slow", "optimize"]):
            insights.append(OracleInsight(
                insight_id=f"INTENT-{uuid.uuid4().hex[:8]}",
                insight_type=InsightType.USER_INTENT,
                title="Performance optimization context",
                description="User focused on performance improvements",
                confidence=ConfidenceLevel.HIGH,
                confidence_score=0.85,
                prediction_horizon=2,
                prevention_actions=[
                    "Profile the code",
                    "Check for N+1 queries",
                    "Review caching strategy",
                    "Analyze algorithm complexity"
                ]
            ))

        return insights

    def _find_optimal_path(self, simulation: ForwardSimulation) -> List[str]:
        """Find the optimal path through the simulation."""
        path = []

        # Filter to low-risk steps
        safe_steps = [s for s in simulation.steps if not s.get("is_risky", False)]

        # Build path through safe steps
        current_step = 0
        for step in sorted(safe_steps, key=lambda x: (x["step"], -x["probability"])):
            if step["step"] > current_step:
                path.append(step["to_state"])
                current_step = step["step"]

            if len(path) >= simulation.depth:
                break

        return path

    def _calculate_simulation_confidence(self, simulation: ForwardSimulation) -> float:
        """Calculate overall confidence in the simulation."""
        if not simulation.steps:
            return 0.5

        # Average probability of steps
        avg_prob = sum(s["probability"] for s in simulation.steps) / len(simulation.steps)

        # Reduce confidence with more risks
        risk_penalty = len(simulation.risk_points) * 0.05

        return max(0.1, min(0.95, avg_prob - risk_penalty))

    def _score_to_level(self, score: float) -> ConfidenceLevel:
        """Convert score to confidence level."""
        if score >= 0.95:
            return ConfidenceLevel.CERTAIN
        elif score >= 0.80:
            return ConfidenceLevel.HIGH
        elif score >= 0.60:
            return ConfidenceLevel.MEDIUM
        elif score >= 0.40:
            return ConfidenceLevel.LOW
        else:
            return ConfidenceLevel.SPECULATIVE

    async def _create_insight_genesis_key(self, insight: OracleInsight):
        """Create Genesis key for insight tracking."""
        if not self._genesis_service:
            return

        try:
            from models.genesis_key_models import GenesisKeyType
            key = self._genesis_service.create_key(
                key_type=GenesisKeyType.ORACLE_INSIGHT,
                what_description=f"Oracle Insight: {insight.title[:50]}",
                who_actor="Oracle",
                where_location=",".join(insight.affected_files[:3]) if insight.affected_files else "system",
                why_reason=f"Predictive analysis - {insight.insight_type.value}",
                how_method="Pattern recognition and forward simulation",
                context_data={
                    "insight_id": insight.insight_id,
                    "type": insight.insight_type.value,
                    "confidence": insight.confidence_score,
                    "horizon": insight.prediction_horizon
                },
                session=self.session
            )
            insight.genesis_key_id = key.key_id
        except Exception as e:
            logger.warning(f"[ORACLE] Genesis key creation failed: {e}")

    async def store_research(
        self,
        topic: str,
        findings: str,
        code_examples: Optional[List[str]] = None,
        source_files: Optional[List[str]] = None
    ) -> ResearchEntry:
        """Store research findings in the AI research knowledge base."""
        entry = ResearchEntry(
            research_id=f"RESEARCH-{uuid.uuid4().hex[:12]}",
            topic=topic,
            findings=findings,
            code_examples=code_examples or [],
            source_files=source_files or [],
            confidence=0.7,
            created_at=datetime.utcnow()
        )

        # Create Genesis key
        if self._genesis_service:
            try:
                from models.genesis_key_models import GenesisKeyType
                key = self._genesis_service.create_key(
                    key_type=GenesisKeyType.RESEARCH_STORED,
                    what_description=f"AI Research: {topic[:50]}",
                    who_actor="Oracle",
                    where_location="ai_research",
                    why_reason="Knowledge base expansion",
                    how_method="Research and pattern analysis",
                    context_data={
                        "research_id": entry.research_id,
                        "topic": topic
                    },
                    session=self.session
                )
                entry.genesis_key_id = key.key_id
            except Exception as e:
                logger.warning(f"[ORACLE] Research genesis key failed: {e}")

        # Store in memory
        self._research[entry.research_id] = entry

        # Store to file system
        await self._persist_research(entry)

        # Store in vector DB for semantic search
        if self._vector_db:
            await self._index_research(entry)

        self.metrics["research_entries"] += 1

        logger.info(f"[ORACLE] Research stored: {topic}")

        return entry

    async def _persist_research(self, entry: ResearchEntry):
        """Persist research to file system."""
        try:
            research_file = self.research_path / f"{entry.research_id}.json"
            with open(research_file, "w") as f:
                json.dump(entry.to_dict(), f, indent=2)
        except Exception as e:
            logger.warning(f"[ORACLE] Research persistence failed: {e}")

    async def _index_research(self, entry: ResearchEntry):
        """Index research in vector DB for semantic search."""
        if not self._vector_db:
            return

        try:
            from embedding.embedder import get_embedder
            embedder = get_embedder()

            text = f"{entry.topic} {entry.findings}"
            embedding = await embedder.embed(text)

            await self._vector_db.upsert(
                collection_name="oracle_research",
                points=[{
                    "id": entry.research_id,
                    "vector": embedding,
                    "payload": entry.to_dict()
                }]
            )
        except Exception as e:
            logger.warning(f"[ORACLE] Research indexing failed: {e}")

    async def search_research(
        self,
        query: str,
        limit: int = 5
    ) -> List[ResearchEntry]:
        """Search research by semantic similarity."""
        if not self._vector_db:
            # Fallback to keyword search
            results = []
            query_lower = query.lower()
            for entry in self._research.values():
                if query_lower in entry.topic.lower() or query_lower in entry.findings.lower():
                    results.append(entry)
            return results[:limit]

        try:
            from embedding.embedder import get_embedder
            embedder = get_embedder()

            embedding = await embedder.embed(query)
            results = await self._vector_db.search(
                collection_name="oracle_research",
                query_vector=embedding,
                limit=limit
            )

            entries = []
            for result in results:
                if result.id in self._research:
                    self._research[result.id].usage_count += 1
                    entries.append(self._research[result.id])

            return entries

        except Exception as e:
            logger.warning(f"[ORACLE] Research search failed: {e}")
            return []

    async def learn_from_outcome(
        self,
        insight_id: str,
        was_accurate: bool,
        actual_outcome: Optional[str] = None
    ):
        """Learn from the accuracy of a prediction."""
        if insight_id not in self._insights:
            return

        insight = self._insights[insight_id]
        insight.was_accurate = was_accurate

        # Update prediction accuracy tracking
        self._prediction_accuracy.append((insight_id, was_accurate))
        if len(self._prediction_accuracy) > 1000:
            self._prediction_accuracy = self._prediction_accuracy[-1000:]

        if was_accurate:
            self.metrics["predictions_correct"] += 1

            # Reinforce the patterns that led to this insight
            for pattern in insight.source_patterns:
                if pattern in self._failure_patterns:
                    self._failure_patterns[pattern]["confidence"] = min(
                        0.99,
                        self._failure_patterns[pattern].get("confidence", 0.7) + 0.05
                    )

        else:
            # Reduce confidence in patterns
            for pattern in insight.source_patterns:
                if pattern in self._failure_patterns:
                    self._failure_patterns[pattern]["confidence"] = max(
                        0.1,
                        self._failure_patterns[pattern].get("confidence", 0.7) - 0.1
                    )

        # Store learning
        await self._queue_learning({
            "type": "prediction_outcome",
            "insight_id": insight_id,
            "was_accurate": was_accurate,
            "actual_outcome": actual_outcome,
            "timestamp": datetime.utcnow().isoformat()
        })

    async def _queue_learning(self, learning: Dict[str, Any]):
        """Queue learning for processing."""
        self._learning_queue.append(learning)

        # Process in batches
        if len(self._learning_queue) >= 10:
            await self._process_learning_queue()

    async def _process_learning_queue(self):
        """Process queued learning items."""
        if not self._learning_queue:
            return

        # Extract patterns from learning
        for item in self._learning_queue:
            if item["type"] == "prediction_outcome":
                # Store as research
                await self.store_research(
                    topic=f"Prediction Accuracy: {item['insight_id']}",
                    findings=f"Prediction was {'accurate' if item['was_accurate'] else 'inaccurate'}. Actual: {item.get('actual_outcome', 'unknown')}"
                )

        self._learning_queue = []

    def get_active_insights(self) -> List[Dict[str, Any]]:
        """Get all active insights."""
        return [
            i.to_dict() for i in self._insights.values()
            if i.is_active and (not i.expires_at or i.expires_at > datetime.utcnow())
        ]

    def get_prediction_accuracy(self) -> float:
        """Get overall prediction accuracy."""
        if not self._prediction_accuracy:
            return 0.0

        correct = sum(1 for _, accurate in self._prediction_accuracy if accurate)
        return correct / len(self._prediction_accuracy)

    def get_metrics(self) -> Dict[str, Any]:
        """Get Oracle metrics."""
        return {
            **self.metrics,
            "prediction_accuracy": self.get_prediction_accuracy(),
            "active_insights": len([i for i in self._insights.values() if i.is_active]),
            "patterns_tracked": len(self._code_patterns),
            "failure_patterns": len(self._failure_patterns),
            "success_patterns": len(self._success_patterns),
            "pending_learnings": len(self._learning_queue)
        }

    def get_research_summary(self) -> Dict[str, Any]:
        """Get summary of stored research."""
        return {
            "total_entries": len(self._research),
            "recent_topics": [
                r.topic for r in sorted(
                    self._research.values(),
                    key=lambda x: x.created_at,
                    reverse=True
                )[:10]
            ],
            "most_used": [
                {"topic": r.topic, "usage": r.usage_count}
                for r in sorted(
                    self._research.values(),
                    key=lambda x: x.usage_count,
                    reverse=True
                )[:5]
            ]
        }
